### ISSUE TITLE
Image thresholding

### ISSUE THREAD

**Issue by danifpdra** [danifpdra/gobi384_driver#4]
@vitoruapt 
Threshold adaptativo
![image](https://user-images.githubusercontent.com/47574905/67968825-efce0780-fbff-11e9-9fa0-e60ed19ca558.png)
Otsu
![image](https://user-images.githubusercontent.com/47574905/67969157-9a462a80-fc00-11e9-80e3-9a4907ab8b10.png)

**Comment by danifpdra** [comment]
![image](https://user-images.githubusercontent.com/47574905/67973512-8999b280-fc08-11e9-8218-21e5a6c83bf1.png)
@vitoruapt 

![image](https://user-images.githubusercontent.com/47574905/67973541-93bbb100-fc08-11e9-88fd-374b54af0afd.png)

**Comment by danifpdra** [comment]
![image](https://user-images.githubusercontent.com/47574905/67974368-39235480-fc0a-11e9-9c0a-def6b1a99833.png)

Calibrated! @vitoruapt

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

good work. We have the camera's optical intrisics then, One important question is how much was the reported RMS error of this calibration. 

This is printed by the ros camera calibration node after calibrating, and gives an idea of how good the calibration is: values of 1-0.8 pixels is a sufficient calibration, 0.3 pixels is a very good calibration.

**Comment by danifpdra** [comment]
![Screenshot from 2019-11-04 11-12-06](https://user-images.githubusercontent.com/47574905/68117042-35d2e600-fef4-11e9-9e67-668359ce1a66.png)

I guess it's good enough @miguelriemoliveira :)

**Comment by miguelriemoliveira** [comment]
Yes, it looks good. Congratulations. 

A couple of suggestions:

I suggest that you don't call your package thermal_camera. There are many other thermal_cameras, how would you call the drivers of a second camera?

Call it gobi_driver (or gobi384_driver) for example.

The yaml file of the calibration should be stored somewhere where everyone has access. 
I suggest that you create a gobi384_calibration pakcage where this is stored. Check 
[RustBot](https://github.com/miguelriemoliveira/RustBot) for an example.

**Comment by vitoruapt** [comment]
Late response... however no longer needed, right?
